/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#ffe9e2",
        "surface-container-low": "#fff1ec",
        "inverse-on-surface": "#ffede7",
        "surface-container-highest": "#ffdbce",
        "surface-tint": "#1b6d24",
        "on-secondary-container": "#00731e",
        "on-tertiary-container": "#e9f2ff",
        "primary": "#0d631b",
        "on-tertiary-fixed-variant": "#004a78",
        "outline-variant": "#bfcaba",
        "surface-container-high": "#ffe2d9",
        "on-secondary": "#ffffff",
        "surface-accent": "#C8E6C9",
        "on-primary": "#ffffff",
        "tertiary": "#00598f",
        "on-tertiary": "#ffffff",
        "outline": "#707a6c",
        "secondary-container": "#91f78e",
        "primary-fixed-dim": "#88d982",
        "on-primary-fixed-variant": "#005312",
        "inverse-primary": "#88d982",
        "on-tertiary-fixed": "#001d34",
        "inverse-surface": "#422b22",
        "on-error-container": "#93000a",
        "surface": "#fff8f6",
        "tertiary-fixed": "#cfe5ff",
        "on-background": "#2b160f",
        "error": "#ba1a1a",
        "warning-orange": "#FF9800",
        "glass-fill": "rgba(255, 255, 255, 0.7)",
        "tertiary-fixed-dim": "#99cbff",
        "secondary-fixed": "#94f990",
        "surface-dim": "#f8d2c4",
        "primary-container": "#2e7d32",
        "glass-stroke": "rgba(255, 255, 255, 0.3)",
        "secondary-fixed-dim": "#78dc77",
        "tertiary-container": "#0072b6",
        "secondary": "#006e1c",
        "on-surface-variant": "#40493d",
        "on-secondary-fixed": "#002204",
        "surface-light": "#FFFFFF",
        "on-error": "#ffffff",
        "background": "#fff8f6",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#002204",
        "surface-bright": "#fff8f6",
        "on-surface": "#2b160f",
        "surface-variant": "#ffdbce",
        "primary-fixed": "#a3f69c",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#cbffc2",
        "on-secondary-fixed-variant": "#005313"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "card-gap": "16px",
        "base": "8px",
        "container-padding-desktop": "64px",
        "section-margin": "80px",
        "gutter": "24px",
        "container-padding-mobile": "20px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "display-hero": ["Inter"],
        "headline-lg": ["Inter"],
        "mono-data": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "mono-data": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
